Update build_dipper.yml

diff --git a/.github/workflows/build_dipper.yml b/.github/workflows/build_dipper.yml
--- a/.github/workflows/build_dipper.yml
+++ b/.github/workflows/build_dipper.yml
@@ -22,6 +22,7 @@ jobs:
       with:
         repository: j2rong4cn/crdroid_kernel_xiaomi_dipper
         ref: 'test'
+        path: kernel_source
 
     - name: Set up swap
       uses: pierotofy/set-swap-space@v1.0
@@ -36,6 +37,7 @@ jobs:
 
     - name: Retrieve information
       run: |
+        cd kernel_source
         sudo timedatectl set-timezone Asia/Shanghai
         echo VERSION=$(date "+%y%m%d_%H%M")-$(git rev-parse HEAD | head -c 7) >> $GITHUB_ENV
         BRANCH=$(git branch --show-current)
@@ -70,6 +72,7 @@ jobs:
         CCACHE_NOHASHDIR: "true"
         CCACHE_HARDLINK: "true"
       run: |
+        cd kernel_source
         export KBUILD_BUILD_HOST=Github-Action
         export KBUILD_BUILD_USER=$(echo ${{ github.actor }} | tr A-Z a-z)
 
@@ -97,12 +100,26 @@ jobs:
 
     - name: Check output files
       run: |
-        ls out/arch/${{ env.ARCH }}/boot/Image* && {
-          mkdir out/outputs
-          mv out/arch/${{ env.ARCH }}/boot/Image.gz-dtb out/outputs/
-          cp .config out/outputs/ 2>/dev/null || cp out/.config out/outputs/ 2>/dev/null || echo "Cannot find .config"
+        ls kernel_source/out/arch/${{ env.ARCH }}/boot/Image* && {
+          mkdir outputs
+          mv kernel_source/out/arch/${{ env.ARCH }}/boot/Image.gz-dtb outputs/
+          cp kernel_source/.config outputs/ 2>/dev/null || cp kernel_source/out/.config outputs/ 2>/dev/null || echo "Cannot find .config"
           echo "CHECK_FILE_IS_OK=true" >> $GITHUB_ENV
         }
+
+    - name: Make boot image
+      if: env.CHECK_FILE_IS_OK == 'true' && secrets.SOURCE_BOOT_IMAGE != ''
+      run: |
+        wget -qO boot-source.img ${{ secrets.SOURCE_BOOT_IMAGE }}
+        if test $? -eq 0 -a -f boot-source.img; then
+          git clone --recursive --depth=1 -j $(nproc --all) https://android.googlesource.com/platform/system/tools/mkbootimg mkbootimg_tools -b master-kernel-build-2022 && {
+            FORMAT_MKBOOTING=$(echo `mkbootimg_tools/unpack_bootimg.py --boot_img=boot-source.img --format mkbootimg`)
+            echo $FORMAT_MKBOOTING
+            mkbootimg_tools/unpack_bootimg.py --boot_img boot-source.img && \
+              cp kernel_source/out/arch/${{ env.ARCH }}/boot/Image out/kernel && \
+              tools/mkbootimg.py $FORMAT_MKBOOTING -o outputs/boot.img
+          }
+        fi
 
     - name: Upload output files
       if: env.CHECK_FILE_IS_OK == 'true'
@@ -110,7 +127,7 @@ jobs:
       with:
         name: dipper-kernel-${{ env.BRANCH }}-${{ env.VERSION }}
         path: |
-          out/outputs/
+          outputs/
 
     - name: Delete old cache
       #if: false
